# CONFIG FILE: GAME OF WHY
# CHARIS CAT 2024

from matplotlib.colors import LinearSegmentedColormap

# ENVIRONMENT SIMULATION SETTINGS #
GRID_SIZE = 100
NUM_STEPS = 50000
CELL_BASE_COUNT = 1 #50

# phase transition boundaries
CELL_STATE_PLASMA_ENERGY = 190
CELL_STATE_GAS_ENERGY = 150
CELL_STATE_LIQUID_ENERGY = 20
CELL_STATE_SOLID_ENERGY = 1
CELL_STATE_INERT_ENERGY = 0

CELL_STATE_PLASMA_COLOR_MIN = 0.0
CELL_STATE_PLASMA_COLOR_MAX = 0.1
CELL_STATE_GAS_COLOR_MIN = 0.7
CELL_STATE_GAS_COLOR_MAX = 0.75
CELL_STATE_LIQUID_COLOR_MIN = 0.5
CELL_STATE_LIQUID_COLOR_MAX = 0.7
CELL_STATE_SOLID_COLOR_MIN = 0.15
CELL_STATE_SOLID_COLOR_MAX = 0.35
CELL_STATE_INERT_COLOR_MIN = 0
CELL_STATE_INERT_COLOR_MAX = 0

CELL_STATE_PLASMA_ALPHA_MIN = 0.7
CELL_STATE_PLASMA_ALPHA_MAX = 0.95
CELL_STATE_GAS_ALPHA_MIN = 0.2
CELL_STATE_GAS_ALPHA_MAX = 0.4
CELL_STATE_LIQUID_ALPHA_MIN = 0.6
CELL_STATE_LIQUID_ALPHA_MAX = 0.9
CELL_STATE_SOLID_ALPHA_MIN = 1
CELL_STATE_INERT_ALPHA_MIN = 1

ORGANISM_STATE_SENTIENT_COLOR_MIN = 0
ORGANISM_STATE_SENTIENT_COLOR_MAX = 0
ORGANISM_STATE_SIMPLE_COLOR_MIN = 0
ORGANISM_STATE_SIMPLE_COLOR_MAX = 0

# environment settings
ENVIRONMENT_VISIBILITY_MULTIPLIER = 1 # raise or lower the amount of visual acuity for cells in the environment

# environmental enrichment settings
ENVIRONMENT_LIGHT_ENRICHMENT = 0.1
ENVIRONMENT_LIGHT_ENRICHMENT_SOURCE_NUM = 5

# environmental decay settings
LIGHT_GRID_DECAY_RATE = 0.05
INERT_GRID_DECAY_RATE = 0.01
ATTRACTIVENESS_GRID_DECAY_RATE = 0.05

# light settings
ENVIRONMENT_LIGHT_CLIP_MIN = 100
ENVIRONMENT_LIGHT_CLIP_MAX = 0


# CELL SIMULATION SETTINGS #
CELL_ROLES = ["general", "structural", "sensory", "reproductive"]

# SPAWNED CELL STATS
CELL_BASE_ATTRACTIVENESS_MIN = 0

# energy
CELL_BASE_ENERGY_MIN = 0
CELL_BASE_ENERGY_MAX = 200

# growth rate
CELL_BASE_GROWTH_RATE_MIN = 30
CELL_BASE_GROWTH_RATE_MAX = 70
CELL_PLASMA_GROWTH_RATE_MIN = 70
CELL_PLASMA_GROWTH_RATE_MAX = 100
CELL_GAS_GROWTH_RATE_MIN = 20
CELL_GAS_GROWTH_RATE_MAX = 50
CELL_LIQUID_GROWTH_RATE_MIN = 60
CELL_LIQUID_GROWTH_RATE_MAX = 90
CELL_MESOPHASE_GROWTH_RATE_MIN = 40
CELL_MESOPHASE_GROWTH_RATE_MAX = 70
CELL_SOLID_GROWTH_RATE_MIN = 10
CELL_SOLID_GROWTH_RATE_MAX = 40
CELL_INERT_GROWTH_RATE_MIN = 0
CELL_INERT_GROWTH_RATE_MAX = 1

# resilience
CELL_BASE_RESILIENCE_MIN = 30
CELL_BASE_RESILIENCE_MAX = 70 
CELL_PLASMA_RESILIENCE_MIN = 50
CELL_PLASMA_RESILIENCE_MAX = 70 
CELL_GAS_RESILIENCE_MIN = 10
CELL_GAS_RESILIENCE_MAX = 30 
CELL_LIQUID_RESILIENCE_MIN = 30
CELL_LIQUID_RESILIENCE_MAX = 50 
CELL_MESOPHASE_RESILIENCE_MIN = 40
CELL_MESOPHASE_RESILIENCE_MAX = 60 
CELL_SOLID_RESILIENCE_MIN = 60
CELL_SOLID_RESILIENCE_MAX = 100 
CELL_INERT_RESILIENCE_MIN = 80
CELL_INERT_RESILIENCE_MAX = 100 

# perception
CELL_BASE_PERCEPTION_MIN = 20
CELL_BASE_PERCEPTION_MAX = 50
CELL_PLASMA_PERCEPTION_MIN = 60
CELL_PLASMA_PERCEPTION_MAX = 90
CELL_GAS_PERCEPTION_MIN = 50
CELL_GAS_PERCEPTION_MAX = 80
CELL_LIQUID_PERCEPTION_MIN = 40
CELL_LIQUID_PERCEPTION_MAX = 70
CELL_MESOPHASE_PERCEPTION_MIN = 80
CELL_MESOPHASE_PERCEPTION_MAX = 100
CELL_SOLID_PERCEPTION_MIN = 5
CELL_SOLID_PERCEPTION_MAX = 15
CELL_INERT_PERCEPTION_MIN = 0
CELL_INERT_PERCEPTION_MAX = 5

# speed
CELL_BASE_SPEED_MIN = 40
CELL_BASE_SPEED_MAX = 80
CELL_PLASMA_SPEED_MIN = 90
CELL_PLASMA_SPEED_MAX = 100
CELL_GAS_SPEED_MIN = 80
CELL_GAS_SPEED_MAX = 100
CELL_LIQUID_SPEED_MIN = 50
CELL_LIQUID_SPEED_MAX = 100
CELL_MESOPHASE_SPEED_MIN = 20
CELL_MESOPHASE_SPEED_MAX = 70
CELL_SOLID_SPEED_MIN = 10
CELL_SOLID_SPEED_MAX = 25
CELL_INERT_SPEED_MIN = 0
CELL_INERT_SPEED_MAX = 10

# light absorption
CELL_BASE_LIGHT_ABSORPTION_MIN = 40
CELL_BASE_LIGHT_ABSORPTION_MAX = 70
CELL_PLASMA_LIGHT_ABSORPTION_MIN = 20
CELL_PLASMA_LIGHT_ABSORPTION_MAX = 40
CELL_GAS_LIGHT_ABSORPTION_MIN = 40
CELL_GAS_LIGHT_ABSORPTION_MAX = 60
CELL_LIQUID_LIGHT_ABSORPTION_MIN = 50
CELL_LIQUID_LIGHT_ABSORPTION_MAX = 70
CELL_MESOPHASE_LIGHT_ABSORPTION_MIN = 0
CELL_MESOPHASE_LIGHT_ABSORPTION_MAX = 100
CELL_SOLID_LIGHT_ABSORPTION_MIN = 20
CELL_SOLID_LIGHT_ABSORPTION_MAX = 40
CELL_INERT_LIGHT_ABSORPTION_MIN = 0
CELL_INERT_LIGHT_ABSORPTION_MAX = 10

# light emission
CELL_BASE_LIGHT_EMISSION_MIN = 0
CELL_BASE_LIGHT_EMISSION_MAX = 30
CELL_PLASMA_LIGHT_EMISSION_MIN = 70
CELL_PLASMA_LIGHT_EMISSION_MAX = 100
CELL_GAS_LIGHT_EMISSION_MIN = 20
CELL_GAS_LIGHT_EMISSION_MAX = 60
CELL_LIQUID_LIGHT_EMISSION_MIN = 5
CELL_LIQUID_LIGHT_EMISSION_MAX = 30
CELL_MESOPHASE_LIGHT_EMISSION_MIN = 0
CELL_MESOPHASE_LIGHT_EMISSION_MAX = 70
CELL_SOLID_LIGHT_EMISSION_MIN = 0
CELL_SOLID_LIGHT_EMISSION_MAX = 20
CELL_INERT_LIGHT_EMISSION_MIN = 0
CELL_INERT_LIGHT_EMISSION_MAX = 10

# life expectancy
CELL_BASE_DEATH_AGE_MIN = 80
CELL_BASE_DEATH_AGE_MAX = 500
CELL_PLASMA_DEATH_AGE_MIN = 80
CELL_PLASMA_DEATH_AGE_MAX = 500
CELL_GAS_DEATH_AGE_MIN = 80
CELL_GAS_DEATH_AGE_MAX = 500
CELL_LIQUID_DEATH_AGE_MIN = 80
CELL_LIQUID_DEATH_AGE_MAX = 500
CELL_MESOPHASE_DEATH_AGE_MIN = 80
CELL_MESOPHASE_DEATH_AGE_MAX = 500
CELL_SOLID_DEATH_AGE_MIN = 80
CELL_SOLID_DEATH_AGE_MAX = 500
CELL_INERT_DEATH_AGE_MIN = 80
CELL_INERT_DEATH_AGE_MAX = 500

# reproduction values
CELL_BASE_MUTATION_RATE_MIN = 0.01
CELL_BASE_MUTATION_RATE_MAX = 0.05
CELL_PLASMA_MUTATION_RATE_MIN = 0.01
CELL_PLASMA_MUTATION_RATE_MAX = 0.05
CELL_GAS_MUTATION_RATE_MIN = 0.01
CELL_GAS_MUTATION_RATE_MAX = 0.05
CELL_LIQUID_MUTATION_RATE_MIN = 0.01
CELL_LIQUID_MUTATION_RATE_MAX = 0.05
CELL_MESOPHASE_MUTATION_RATE_MIN = 0.01
CELL_MESOPHASE_MUTATION_RATE_MAX = 0.05
CELL_SOLID_MUTATION_RATE_MIN = 0.01
CELL_SOLID_MUTATION_RATE_MAX = 0.05
CELL_INERT_MUTATION_RATE_MIN = 0.01
CELL_INERT_MUTATION_RATE_MAX = 0.05

CELL_FERTILITY_AGE_MIN = 10
CELL_FERTILITY_AGE_MAX = 90

CELL_FERTILITY_ENERGY_MIN = 300 # min energy a cell needs to reproduce

CELL_FERTILITY_CHANCE_MIN = 0.02 

CELL_REPRODUCTION_FAILURE_COST = 2 
CELL_REPRODUCTION_SUCCESS_COST = 5 # multiplier for how much energy loss is incurred from reproducing

CELL_BABY_MUTATION_GROWTH_MIN = -0.1f
CELL_BABY_MUTATION_GROWTH_MAX = 0.1
CELL_BABY_MUTATION_RESILIENCE_MIN = -0.1
CELL_BABY_MUTATION_RESILIENCE_MAX = 0.1
CELL_BABY_MUTATION_SPEED_MIN = -0.05
CELL_BABY_MUTATION_SPEED_MAX = 0.05
CELL_BABY_MUTATION_PERCEPTION_MIN = -0.1
CELL_BABY_MUTATION_PERCEPTION_MAX = 0.1

# death values
CELL_DEATH_AGE_MIN = 80
CELL_DEATH_AGE_MAX = 500

CELL_DEATH_REASON_SQUISH = "squish"
CELL_DEATH_REASON_AGE = "age"
CELL_DEATH_REASON_STARVATION = "starvation"

CELL_DEATH_RELEASE_LIGHT = 0.5

CELL_DEATH_RELEASE_INERT = 300 # maybe make equivalent to the cells final weight, eventually

CELL_DEATH_RELEASE_SQUISH_MIN = 0.4
CELL_DEATH_RELEASE_SQUISH_MAX = 0.6

CELL_DECAY_ENERGY_MULTIPLIER = 1
CELL_DECAY_AGE_PER_TURN = 1

# social norms
CELL_ATTRACTIVENESS_NORM_ENERGY = 100
CELL_ATTRACTIVENESS_NORM_AGE = 100
CELL_ATTRACTIVENESS_NORM_GROWTH = 100
CELL_ATTRACTIVENESS_NORM_RESILIENCE = 100
CELL_ATTRACTIVENESS_NORM_PERCEPTION = 100
CELL_ATTRACTIVENESS_NORM_STRENGTH = 100
CELL_ATTRACTIVENESS_NORM_SPEED = 100
CELL_ATTRACTIVENESS_NORM_LIGHT_EMISSION = 100

# MOVEMENT SIMULATION SETTINGS #
CELL_MOVE_BLOCKED_MAX = 4
CELL_MOVE_ENERGY_MIN = 1

# VISUALISATION SETTINGS #
VISUALISATION_BASE_ENERGY_TOP_RECORD = 100
INERT_GRID_TRANSPARENCY = 0.8
ATTRACTIVENESS_GRID_TRANSPARENCY = 0.6
LIGHT_GRID_TRANSPARENCY = 0.6

# Define RGBA colors for the gradient: transparent -> green -> brown
colors = [
    (0, 0, 0, 0),      # transparent
    (0.1, 0.3, 0.1, 1),  # green
    (0.4, 0.3, 0.2, 1),  # brown
    (0.2, 0.2, 0.2, 1)   # grey
]

# Create the colormap
terrain_colormap = LinearSegmentedColormap.from_list("terrain_colormap", colors)

colors = [
        (0.0, (1, 1, 1, 0)),
        (0.3, (0.5, 0.1, 0.5, 0.2)),
        (0.7, (1.0, 0.5, 0.0, 0.6)),
        (1.0, (1.0, 1.0, 0.0, 0.8)),
    ]
    
purple_yellow_colormap = LinearSegmentedColormap.from_list("purple_yellow", colors)