# CONFIG FILE: GAME OF WHY
# CHARIS CAT 2024

# ENVIRONMENT SIMULATION SETTINGS
GRID_SIZE = 1000
NUM_STEPS = 50000
INITIAL_CELL_COUNT = 1000 #50

# phase transition boundaries
PLASMA_ENERGY = 190
GAS_ENERGY = 150
LIQUID_ENERGY = 20
SOLID_ENERGY = 1
INERT_ENERGY = 0

# CELL SIMULATION SETTINGS
CELL_ROLES = ["general", "structural", "sensory", "reproductive"]

# cell base stats
CELL_BASE_MUTATION_RATE = 0.01
CELL_BASE_MIN_GROWTH_RATE = 0.8
CELL_BASE_MAX_GROWTH_RATE = 1.2
CELL_BASE_MIN_RESILIENCE = 0.8
CELL_BASE_MAX_RESILIENCE = 1.2 
CELL_BASE_MIN_PERCEPTION = 0.1
CELL_BASE_MAX_PERCEPTION = 0.5
CELL_BASE_MIN_SPEED = 0.5
CELL_BASE_MAX_SPEED = 1.5
CELL_BASE_LIGHT_EMISSION = 0

# reproduction values
CELL_FERTILITY_MIN_AGE = 10
CELL_FERTILITY_MAX_AGE = 90
CELL_FERTILITY_ENERGY = 300 # min energy a cell needs to reproduce

CELL_FERTILITY_CHANCE = 0.02 
CELL_REPRODUCTION_FAILURE_COST = 2 
CELL_REPRODUCTION_SUCCESS_COST = 5 # multiplier for how much energy loss is incurred from reproducing
